### ISSUE TITLE
Documentation question

### ISSUE THREAD

**Issue by fbennett** [fcheslack/libZoteroJS#10]
I would like to use libZoteroJS for a local project (pulling reading lists and staff publications for use in faculty pages). The plan for the API bit will just be to pull CSL-JSON records from a Zotero group, filtered by tag.

I'm good with the Zotero Web API, but from the source and the tests, I'm not sure how the incantations to authenticate and grab the records by search would be expressed in libZoteroJS. I'm a perpetual novice at programming, and I'm probably just overlooking the relevant documentation; but if anyone can point me in the right direction, it would be a great help.

**Comment by fbennett** [comment]
From #3, I'm able to fetch all of the items in the library. I've dumped the keys on the Zotero and Zotero.lib objects, but I don't see anything in there about search, apart from stuff about saved searches on server-side.

To filter items by tag, is it necessary to save a search in the client and sync? Or is there a way of filtering through the libZoteroJS interface? I'm stuck.

**Comment by fbennett** [comment]
Hmm. Maybe I'm barking up the wrong tree here. From the source code, it looks like `buildItemDisplayView()` is able to filter by tags, but does not work in `node.js` because an indexed database it depends on is not available there. I guess I should use raw API calls to fetch by tag?

Closing this. (If filtering is possible, let me know and I'll reopen.)

**Comment by fcheslack** [comment]
Alas, you're not missing anything regarding documentation.

I'll add some more examples later today, but generally the functions like loadItems can be passed an object with values valid for the API https://www.zotero.org/support/dev/web_api/v3/basics#read_requests

so you could do 
loadItems({tag:'panda'})

**Comment by fbennett** [comment]
Oh, yay. Thanks Faolan!

**Comment by fbennett** [comment]
... and happy to report that it works a treat. Now I just have to work out how to reverse my mlzsync mess in the Extra field after download. :-)
