### ISSUE TITLE
Use something like superagent for network requests

### ISSUE THREAD

**Issue by fcheslack** [fcheslack/libZoteroJS#12]
If we want to support both browsers and node we probably need to switch to an abstracted http request library that supports both environments like [superagent](https://github.com/visionmedia/superagent). None of the node implementations of xmlhttprequest I've looked at are complete or up to date.

**Comment by tnajdek** [comment]
Would using fetch be an option? It's [support in browsers](http://caniuse.com/#search=fetch) is growing nicely and there are really [good polyfills](https://github.com/matthew-andrews/isomorphic-fetch).

**Comment by fcheslack** [comment]
Yeah, that's an option. I haven't looked too closely at the polyfills, but if they polyfill all of the basic networking interfaces the fetch API uses, I think that would be a good idea. All our network requests are already done through Zotero.Net, so we can do pretty much whatever we want with it, but I like the idea of being able to use those actually standardized Headers/Request/Response interfaces (and expose them to consumers).

I liked the idea of superagent because it already has plugin support for things like throttling, but that's not too bad to add ourselves so I think I prefer the standardized interfaces.

**Comment by fcheslack** [comment]
https://github.com/fcheslack/libZoteroJS/commit/7ae4f455f7e03a6432eb4930def4c975d2c3f073
